import { UserRole } from "../../generated/prisma";

interface userToCreate {
  name: string;
  lastName: string;
  password: string;
  email: string;
  bio?: string;
  phone?: string;
  role: UserRole;
  facultyId?: number;
  avatar?: string;
  coverImage?: string;
}

export const usersToCreate: userToCreate[] = [
  // 🧑‍🎓 STUDENTS
  {
    name: "Aidar",
    lastName: "Saparov",
    password: "password123",
    email: "aidar@mail.com",
    bio: "Люблю React и TypeScript. Сейчас изучаю React Native и backend на NestJS, хочу стать fullstack-разработчиком.",
    phone: "+77010000001",
    role: UserRole.STUDENT,
    facultyId: 1,
    avatar: "https://i.pravatar.cc/150?img=1",
    coverImage: "https://picsum.photos/seed/aidar/800/200",
  },
  {
    name: "Dana",
    lastName: "Nurlybekova",
    password: "password123",
    email: "dana@mail.com",
    bio: "UI/UX дизайнер и студентка 3 курса. Занимаюсь проектированием мобильных интерфейсов и изучаю анимации в Figma.",
    role: UserRole.STUDENT,
    facultyId: 2,
    avatar: "https://i.pravatar.cc/150?img=2",
    coverImage: "https://picsum.photos/seed/dana/800/200",
  },
  {
    name: "Erlan",
    lastName: "Tulegenov",
    password: "password123",
    email: "erlan@mail.com",
    bio: "Backend разработчик на NestJS.",
    phone: "+77010000003",
    role: UserRole.STUDENT,
    facultyId: 3,
    avatar: "https://i.pravatar.cc/150?img=3",
    coverImage: "https://picsum.photos/seed/erlan/800/200",
  },
  {
    name: "Amina",
    lastName: "Sadykova",
    password: "password123",
    email: "amina@mail.com",
    bio: "Изучаю машинное обучение, участвую в хакатонах и люблю решать задачи на Kaggle. В будущем хочу работать в сфере Data Science.",
    role: UserRole.STUDENT,
    facultyId: 4,
    avatar: "https://i.pravatar.cc/150?img=4",
    coverImage: "https://picsum.photos/seed/amina/800/200",
  },
  {
    name: "Nursultan",
    lastName: "Kairatov",
    password: "password123",
    email: "nursultan@mail.com",
    phone: "+77010000005",
    role: UserRole.STUDENT,
    facultyId: 5,
    avatar: "https://i.pravatar.cc/150?img=5",
    coverImage: "https://picsum.photos/seed/nursultan/800/200",
  },
  {
    name: "Mira",
    lastName: "Ospanova",
    password: "password123",
    email: "mira@mail.com",
    bio: "Пишу диплом по кибербезопасности.",
    role: UserRole.STUDENT,
    facultyId: 1,
    avatar: "https://i.pravatar.cc/150?img=6",
    coverImage: "https://picsum.photos/seed/mira/800/200",
  },
  {
    name: "Dias",
    lastName: "Akhmetov",
    password: "password123",
    email: "dias@mail.com",
    bio: "Люблю C++ и алгоритмы. Участвую в олимпиадах и изучаю структуры данных, графы и динамическое программирование.",
    phone: "+77010000007",
    role: UserRole.STUDENT,
    facultyId: 2,
    avatar: "https://i.pravatar.cc/150?img=7",
    coverImage: "https://picsum.photos/seed/dias/800/200",
  },
  {
    name: "Aliya",
    lastName: "Yermekova",
    password: "password123",
    email: "aliya@mail.com",
    bio: "PM в студенческом стартапе. Руководила командой из 6 человек при создании приложения для университета.",
    role: UserRole.STUDENT,
    facultyId: 3,
    avatar: "https://i.pravatar.cc/150?img=8",
    coverImage: "https://picsum.photos/seed/aliya/800/200",
  },
  {
    name: "Rustem",
    lastName: "Bekturov",
    password: "password123",
    email: "rustem@mail.com",
    phone: "+77010000009",
    role: UserRole.STUDENT,
    facultyId: 4,
    avatar: "https://i.pravatar.cc/150?img=9",
    coverImage: "https://picsum.photos/seed/rustem/800/200",
  },
  {
    name: "Karina",
    lastName: "Serikova",
    password: "password123",
    email: "karina@mail.com",
    bio: "Фанатка UI-дизайна и иллюстрации. В свободное время создаю дизайн-концепты для мобильных приложений и веду блог о цифровом искусстве.",
    role: UserRole.STUDENT,
    facultyId: 5,
    avatar: "https://i.pravatar.cc/150?img=10",
    coverImage: "https://picsum.photos/seed/karina/800/200",
  },

  // 👨‍🏫 TEACHERS
  {
    name: "Askar",
    lastName: "Temirbayev",
    password: "password123",
    email: "askar.teacher@mail.com",
    bio: "Преподаю основы программирования и баз данных. Люблю объяснять сложные вещи простыми словами.",
    phone: "+77020000001",
    role: UserRole.TEACHER,
    facultyId: 1,
    avatar: "https://i.pravatar.cc/150?img=11",
    coverImage: "https://picsum.photos/seed/askar/800/200",
  },
  {
    name: "Svetlana",
    lastName: "Kuznetsova",
    password: "password123",
    email: "svetlana.teacher@mail.com",
    bio: "Доцент кафедры информационных систем. Автор учебников по алгоритмам и анализу данных.",
    role: UserRole.TEACHER,
    facultyId: 2,
    coverImage: "https://picsum.photos/seed/svetlana/800/200",
  },
  {
    name: "Marat",
    lastName: "Abdrakhmanov",
    password: "password123",
    email: "marat.teacher@mail.com",
    bio: "Преподаю сетевые технологии, интересуюсь безопасностью и инфраструктурой Linux.",
    role: UserRole.TEACHER,
    facultyId: 3,
    avatar: "https://i.pravatar.cc/150?img=13",
    coverImage: "https://picsum.photos/seed/marat/800/200",
  },
  {
    name: "Gulnara",
    lastName: "Mukasheva",
    password: "password123",
    email: "gulnara.teacher@mail.com",
    bio: "Кандидат технических наук, веду курсы по анализу данных и статистике.",
    role: UserRole.TEACHER,
    facultyId: 4,
  },
  {
    name: "Sergey",
    lastName: "Ivanov",
    password: "password123",
    email: "sergey.teacher@mail.com",
    bio: "Преподаватель инженерного факультета, специализируюсь на автоматизации и робототехнике.",
    phone: "+77020000005",
    role: UserRole.TEACHER,
    facultyId: 5,
    avatar: "https://i.pravatar.cc/150?img=15",
    coverImage: "https://picsum.photos/seed/sergey/800/200",
  },

  // 🧑‍💼 ADMINS
  {
    name: "Arman",
    lastName: "Bekov",
    password: "password123",
    email: "arman.admin@mail.com",
    bio: "Администратор системы. Отвечаю за работу серверов и управление пользователями.",
    phone: "+77030000001",
    role: UserRole.ADMIN,
    avatar: "https://i.pravatar.cc/150?img=16",
    coverImage: "https://picsum.photos/seed/arman/800/200",
  },
  {
    name: "Laura",
    lastName: "Tulegenova",
    password: "password123",
    email: "laura.admin@mail.com",
    bio: "Главный администратор платформы. Курирую проекты, связанные с интеграцией AI и аналитикой.",
    phone: "+77030000002",
    role: UserRole.ADMIN,
    avatar: "https://i.pravatar.cc/150?img=17",
    coverImage: "https://picsum.photos/seed/laura/800/200",
  },
];
